# Generated by Django 3.0.8 on 2021-11-28 11:35

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import template.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Templates',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('authorUID', models.CharField(max_length=100)),
                ('likes', models.IntegerField(default=0)),
                ('downloaded', models.IntegerField(default=0)),
                ('keywordsSearch', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=None)),
                ('isPremium', models.BooleanField(default=False)),
                ('colors', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('red', 'Đỏ'), ('orange', 'Cam'), ('yellow', 'Vàng'), ('blue', 'Xanh dương'), ('green', 'Xanh lá'), ('purple', 'Tím'), ('brown', 'Nâu'), ('white', 'Trắng'), ('black', 'Đen')], default='', max_length=10), size=None)),
                ('styles', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('sport', 'Thể thao'), ('creative', 'Sáng tạo'), ('cute', 'Đáng yêu'), ('funny', 'Hài hước'), ('modern', 'Hiện đại'), ('simple', 'Đơn giản'), ('vintage', 'Hoài cổ'), ('elegant', 'Tao nhã'), ('cartoon', 'Hoạt hình'), ('minimalist', 'Tối giản')], default='', max_length=20), size=None)),
                ('topics', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('education', 'Giáo dục'), ('business', 'Kinh doanh'), ('marketing', 'Marketing'), ('medical', 'Y học'), ('multiPurpose', 'Đa mục đích'), ('infoGraphic', 'Sơ đồ')], default='', max_length=20), size=None)),
                ('templates_file', models.FileField(upload_to=template.models.create_directory)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SlideImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide_images', models.ImageField(upload_to=template.models.create_imgs_directory)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slide_image', to='template.Templates')),
            ],
        ),
    ]
